### ISSUE TITLE
Does not work with Debian 9 Stretch

### ISSUE THREAD

**Issue by dashwhale** [exasol/sqlalchemy-exasol#72]
Module does not work on Debian 9. Trying to do a select on a table. Python2 or 3 does not make any difference. It works with Debian 8.

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    connection = engine.connect()
  File "/home/user/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2102, in connect
    return self._connection_cls(self, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 90, in __init__
    if connection is not None else engine.raw_connection()
  File "/home/user/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2188, in raw_connection
    self.pool.unique_connection, _connection)
  File "/home/user/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/home/user/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/home/user/.local/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/user/.local/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/user/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/home/user/.local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 345, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/user/.local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 782, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/user/.local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 532, in checkout
    rec = pool._do_get()
  File "/home/user/.local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 1186, in _do_get
    self._dec_overflow()
  File "/home/user/.local/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/user/.local/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/home/user/.local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 1183, in _do_get
    return self._create_connection()
  File "/home/user/.local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 350, in _create_connection
    return _ConnectionRecord(self)
  File "/home/user/.local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 477, in __init__
    self.__connect(first_connect_check=True)
  File "/home/user/.local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 667, in __connect
    connection = pool._invoke_creator(self)
  File "/home/user/.local/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/user/.local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 410, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('HY000', 'The driver did not supply an error!') (Background on this error at: http://sqlalche.me/e/dbapi)

**Comment by jank** [comment]
Thank you for pointing this out.
Automated tests run on Travis-Ci which supports Ubuntu. Currently this is
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
However, this dialect is also used in production on Debian 8. Upgrade to 9 will happen, no timeline fixed yet. If you could provide more details on the error this would be helpful. 
From the trace it is hard to guess, but I would start by checking/trying:
* is the EXASOL driver installed (not shipped with the dialect)
* try connecting to the EXASOL DB using plain pyodbc (if this does not work it is an underlying driver issue)

**Comment by jank** [comment]
Master branch now builds on Ubuntu bionic. According to sources I found, bionic is a rough equivalent of Debian 9.
https://askubuntu.com/questions/445487/what-debian-version-are-the-different-ubuntu-versions-based-on
